definitions:
  controller.ErrorResponse:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
  controller.NewsAPIResonse:
    properties:
      articles:
        items:
          $ref: '#/definitions/news_api.Article'
        type: array
      totalResults:
        type: integer
    type: object
  news_api.Article:
    properties:
      author:
        type: string
      content:
        type: string
      description:
        type: string
      publishedAt:
        type: string
      source:
        $ref: '#/definitions/news_api.ArticleSource'
      title:
        type: string
      url:
        type: string
      urlToImage:
        type: string
    type: object
  news_api.ArticleSource:
    properties:
      id: {}
      name:
        type: string
    type: object
info:
  contact: {}
  description: 最新のニュースを取得するAPIです
  license:
    name: taichi kanaya
  title: NewsAPI
  version: "1.0"
paths:
  /news-api:
    get:
      description: NewsAPIの記事を取得する( https://newsapi.org/docs/endpoints/everything
        のエンドポイントを使用します)
      parameters:
      - description: query
        in: query
        name: query
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: NewsAPIの記事情報を返します
          schema:
            $ref: '#/definitions/controller.NewsAPIResonse'
        "400":
          description: バリデーションエラーメッセージを返します
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: システムエラーメッセージを返します
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: NewsAPIの記事を取得する
      tags:
      - news-api
swagger: "2.0"
